[package]
name = "medic"
version = "0.1.3"
authors = ["sts10 <sschlinkert@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.8.6"
rpassword = "2.0.0"
sha1 = "0.6.0"
# keepass = "0.3.0"
keepass = { git = "https://github.com/sseemayer/keepass-rs" }
indicatif = "0.11.0"
zxcvbn = "1.0.0"
csv = "1"
